<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Triamec" Id="{23682737-03b6-4da5-afce-708bad80b677}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Triamec
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Triamec">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>